name: Java CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Compile
        run: mvn compile

      - name: Small tests
        run: mvn test

      - name: All tests
        run: mvn integration-test
